Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -6,8 +6,11 @@ inputs:
   owner:
     description: 'Repository Owner'
     required: true
-  repository:
-    description: 'Repository name'
+  # repository:
+  #   description: 'Repository name'
+  #   required: true
+  repositories:
+    description: 'Comma-separated list of repository names'
     required: true
   access-token:
     description: 'PAT with repository scope (https://github.com/settings/tokens)'
@@ -30,43 +33,53 @@ runs:
   steps:
     - name: Clone repository
       run: |
-        if [ -z "${{ inputs.access-token }}" ]; then
-          if [ -z "${{ inputs.depth }}" ]; then
-            if [ "${{ inputs.submodule }}" = "true" ]; then
-              git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
+        IFS=',' read -ra REPO_ARRAY <<< "${{ inputs.repositories }}"
+        for REPO in "${REPO_ARRAY[@]}"; do
+          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" -H "Authorization: token ${{ inputs.access-token }}" https://api.github.com/repos/${{ inputs.owner }}/$REPO)
+          if [ "$STATUS_CODE" = "404" ]; then
+            curl -X POST -H "Authorization: token ${{ inputs.access-token }}" \
+              -d "{\"name\":\"$REPO\", \"private\": true}" \
+              https://api.github.com/user/repos
+          fi
+      
+          if [ -z "${{ inputs.access-token }}" ]; then
+            if [ -z "${{ inputs.depth }}" ]; then
+              if [ "${{ inputs.submodule }}" = "true" ]; then
+                git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/$REPO.git  --recursive
+              else
+                git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/$REPO.git
+              fi
             else
-              git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
+              if [ "${{ inputs.submodule }}" = "true" ]; then
+                git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://github.com/${{ inputs.owner }}/$REPO.git  --recursive
+              else
+                git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://github.com/${{ inputs.owner }}/$REPO.git
+              fi
             fi
           else
-            if [ "${{ inputs.submodule }}" = "true" ]; then
-              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
+            if [ -z "${{ inputs.depth }}" ]; then
+              if [ "${{ inputs.submodule }}" = "true" ]; then
+                git clone --branch "${{ inputs.branch }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/$REPO.git  --recursive
+              else
+                git clone --branch "${{ inputs.branch }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/$REPO.git
+              fi
             else
-              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
+              if [ "${{ inputs.submodule }}" = "true" ]; then
+                git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/$REPO.git  --recursive
+              else
+                git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/$REPO.git
+              fi
             fi
           fi
-        else
-          if [ -z "${{ inputs.depth }}" ]; then
-            if [ "${{ inputs.submodule }}" = "true" ]; then
-              git clone --branch "${{ inputs.branch }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
-            else
-              git clone --branch "${{ inputs.branch }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
-            fi
+      
+          if [ -d "$REPO" ]; then
+            echo "Cloned $REPO repository successfully."
+            echo "Access the repository content using \"cd $REPO.\""
           else
-            if [ "${{ inputs.submodule }}" = "true" ]; then
-              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
-            else
-              git clone --branch "${{ inputs.branch }}" --depth="${{ inputs.depth }}" https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
-            fi
+            echo "Error: Couldn't clone $REPO repository. Check the inputs or the PAT scope."
+            exit 1
           fi
-        fi
-
-        if [ -d "${{ inputs.repository }}" ]; then
-          echo "Cloned ${{ inputs.repository }} repository successfully."
-          echo "Access the repository content using \"cd ${{ inputs.repository }}.\""
-        else
-          echo "Error: Couldn't clone ${{ inputs.repository }} repository. Check the inputs or the PAT scope."
-          exit 1
-        fi
+        done
       shell: bash
 
 branding:
